apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-saker
  namespace: min-side
  labels:
    team: min-side
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  envFrom:
    - secret: mine-saker-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /mine-saker/internal/isAlive
    initialDelay: 10
  readiness:
    path: /mine-saker/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /mine-saker/internal/metrics
  replicas:
    min: 2
    max: 4
  accessPolicy:
    outbound:
      external:
        - host: "person.nav.no"
        - host: "www.nav.no"
  ingresses:
    - "https://person.nav.no/mine-saker"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
